// The copy for Supabase Auth's own emails (supabase/templates/*.html), generated by
// scripts/build-auth-email-templates.ts. These aren't part of the app's i18next bundle (they're
// rendered once, at build time, into static Go-template HTML that gotrue fills in — not at request
// time by the running app), so they live here as a small typed data file instead: the one place this
// copy is written, in both languages, reused by the generator for every template.
//
// `linkFallback` is shown for every link-based flow ("paste this link…"); the generator appends the
// literal `{{ .ConfirmationURL }}` after it. `note` is an optional extra reassurance line
// ("if you didn't request this…"). `newEmailMarker` in email_change's paragraph is replaced by the
// generator with `<strong>{{ .NewEmail }}</strong>` (a Go variable, not static copy).

export const NEW_EMAIL_MARKER = "__NEW_EMAIL__";

export type AuthEmailType = "confirmation" | "invite" | "recovery" | "magic_link" | "email_change" | "reauthentication";

export type AuthEmailCopy = {
  heading: string;
  paragraph: string;
  cta: string;
  linkFallback?: string;
  note?: string;
};

export type AuthEmailLocaleCopy = Record<"en" | "pl", AuthEmailCopy>;

export const AUTH_EMAIL_COPY: Record<AuthEmailType, AuthEmailLocaleCopy> = {
  confirmation: {
    en: {
      heading: "Confirm your email address",
      paragraph: "Follow the link below to confirm this email address and finish signing up for RenoVision.",
      cta: "Confirm email address",
      linkFallback: "If the button doesn't work, paste this link into your browser:",
    },
    pl: {
      heading: "Potwierdź adres e-mail",
      paragraph: "Kliknij poniższy link, aby potwierdzić adres e-mail i dokończyć rejestrację w RenoVision.",
      cta: "Potwierdź adres e-mail",
      linkFallback: "Jeśli przycisk nie działa, wklej ten link w przeglądarce:",
    },
  },
  invite: {
    en: {
      heading: "You've been invited to RenoVision",
      paragraph: "You've been invited to create a RenoVision account. Follow the link below to accept the invitation.",
      cta: "Accept invitation",
      linkFallback: "If the button doesn't work, paste this link into your browser:",
    },
    pl: {
      heading: "Zaproszono Cię do RenoVision",
      paragraph: "Zaproszono Cię do założenia konta w RenoVision. Kliknij poniższy link, aby zaakceptować zaproszenie.",
      cta: "Zaakceptuj zaproszenie",
      linkFallback: "Jeśli przycisk nie działa, wklej ten link w przeglądarce:",
    },
  },
  recovery: {
    en: {
      heading: "Reset your password",
      paragraph: "We received a request to reset your RenoVision password. Follow the link below to choose a new one.",
      cta: "Reset password",
      linkFallback: "If the button doesn't work, paste this link into your browser:",
      note: "If you didn't request this, you can safely ignore this email.",
    },
    pl: {
      heading: "Zresetuj hasło",
      paragraph: "Otrzymaliśmy prośbę o zresetowanie hasła do RenoVision. Kliknij poniższy link, aby ustawić nowe hasło.",
      cta: "Zresetuj hasło",
      linkFallback: "Jeśli przycisk nie działa, wklej ten link w przeglądarce:",
      note: "Jeśli to nie Ty wysłałeś tę prośbę, możesz zignorować tę wiadomość.",
    },
  },
  magic_link: {
    en: {
      heading: "Your sign-in link",
      paragraph: "Follow the link below to sign in to RenoVision. This link expires shortly and can only be used once.",
      cta: "Sign in",
      linkFallback: "If the button doesn't work, paste this link into your browser:",
    },
    pl: {
      heading: "Twój link do logowania",
      paragraph: "Kliknij poniższy link, aby zalogować się do RenoVision. Link wkrótce wygaśnie i może zostać użyty tylko raz.",
      cta: "Zaloguj się",
      linkFallback: "Jeśli przycisk nie działa, wklej ten link w przeglądarce:",
    },
  },
  email_change: {
    en: {
      heading: "Confirm your new email address",
      paragraph: `Follow the link below to confirm ${NEW_EMAIL_MARKER} as your new RenoVision email address.`,
      cta: "Confirm new email address",
      linkFallback: "If the button doesn't work, paste this link into your browser:",
      note: "If you didn't request this change, you can safely ignore this email.",
    },
    pl: {
      heading: "Potwierdź nowy adres e-mail",
      paragraph: `Kliknij poniższy link, aby potwierdzić ${NEW_EMAIL_MARKER} jako nowy adres e-mail w RenoVision.`,
      cta: "Potwierdź nowy adres e-mail",
      linkFallback: "Jeśli przycisk nie działa, wklej ten link w przeglądarce:",
      note: "Jeśli to nie Ty poprosiłeś o tę zmianę, możesz zignorować tę wiadomość.",
    },
  },
  reauthentication: {
    en: {
      heading: "Your verification code",
      paragraph: "Use the code below to verify your identity on RenoVision. It expires shortly.",
      cta: "", // no button: the code itself is the content (see the generator)
      note: "If you didn't request this, you can safely ignore this email.",
    },
    pl: {
      heading: "Twój kod weryfikacyjny",
      paragraph: "Użyj poniższego kodu, aby zweryfikować swoją tożsamość w RenoVision. Kod wkrótce wygaśnie.",
      cta: "",
      note: "Jeśli to nie Ty wysłałeś tę prośbę, możesz zignorować tę wiadomość.",
    },
  },
};

export const AUTH_EMAIL_FOOTER = {
  en: "RenoVision — renovation tracking.",
  pl: "RenoVision — śledzenie remontu.",
};

/** Subject lines (also localized by the generator into one Go if/else expression per type). */
export const AUTH_EMAIL_SUBJECT: Record<AuthEmailType, Record<"en" | "pl", string>> = {
  confirmation: { en: "Confirm your email address", pl: "Potwierdź adres e-mail" },
  invite: { en: "You've been invited to RenoVision", pl: "Zaproszono Cię do RenoVision" },
  recovery: { en: "Reset your password", pl: "Zresetuj hasło" },
  magic_link: { en: "Your sign-in link", pl: "Twój link do logowania" },
  email_change: { en: "Confirm your new email address", pl: "Potwierdź nowy adres e-mail" },
  reauthentication: { en: "Your verification code", pl: "Twój kod weryfikacyjny" },
};
