/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteImport } from './routes/_authed'
import { Route as loginRouteImport } from './routes/login'
import { Route as indexRouteImport } from './routes/index'
import { Route as settingsRouteImport } from './routes/settings'
import { Route as projectsRouteImport } from './routes/projects'
import { Route as projectLayoutRouteImport } from './routes/project/layout'
import { Route as projectOverviewRouteImport } from './routes/project/overview'
import { Route as projectBudgetRouteImport } from './routes/project/budget'
import { Route as projectChatRouteImport } from './routes/project/chat'
import { Route as projectDesignRouteImport } from './routes/project/design'
import { Route as projectKnowledgeRouteImport } from './routes/project/knowledge'
import { Route as projectPhotosRouteImport } from './routes/project/photos'
import { Route as projectPlanRouteImport } from './routes/project/plan'
import { Route as projectProgressRouteImport } from './routes/project/progress'
import { Route as projectStagesRouteImport } from './routes/project/stages'
import { Route as projectTeamRouteImport } from './routes/project/team'
import { Route as projectUpdatesRouteImport } from './routes/project/updates'

const authedRoute = authedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedRoute,
} as any)
const settingsRoute = settingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authedRoute,
} as any)
const projectsRoute = projectsRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => authedRoute,
} as any)
const projectLayoutRoute = projectLayoutRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => authedRoute,
} as any)
const projectOverviewRoute = projectOverviewRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectBudgetRoute = projectBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectChatRoute = projectChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectDesignRoute = projectDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectKnowledgeRoute = projectKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectPhotosRoute = projectPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectPlanRoute = projectPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectProgressRoute = projectProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectStagesRoute = projectStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectTeamRoute = projectTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectUpdatesRoute = projectUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => projectLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/login': typeof loginRoute
  '/settings': typeof settingsRoute
  '/projects/': typeof projectsRoute
  '/projects/$projectId': typeof projectLayoutRouteWithChildren
  '/projects/$projectId/': typeof projectOverviewRoute
  '/projects/$projectId/budget': typeof projectBudgetRoute
  '/projects/$projectId/chat': typeof projectChatRoute
  '/projects/$projectId/design': typeof projectDesignRoute
  '/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/projects/$projectId/photos': typeof projectPhotosRoute
  '/projects/$projectId/plan': typeof projectPlanRoute
  '/projects/$projectId/progress': typeof projectProgressRoute
  '/projects/$projectId/stages': typeof projectStagesRoute
  '/projects/$projectId/team': typeof projectTeamRoute
  '/projects/$projectId/updates': typeof projectUpdatesRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/': typeof indexRoute
  '/settings': typeof settingsRoute
  '/projects': typeof projectsRoute
  '/projects/$projectId': typeof projectOverviewRoute
  '/projects/$projectId/budget': typeof projectBudgetRoute
  '/projects/$projectId/chat': typeof projectChatRoute
  '/projects/$projectId/design': typeof projectDesignRoute
  '/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/projects/$projectId/photos': typeof projectPhotosRoute
  '/projects/$projectId/plan': typeof projectPlanRoute
  '/projects/$projectId/progress': typeof projectProgressRoute
  '/projects/$projectId/stages': typeof projectStagesRoute
  '/projects/$projectId/team': typeof projectTeamRoute
  '/projects/$projectId/updates': typeof projectUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof authedRouteWithChildren
  '/login': typeof loginRoute
  '/_authed/': typeof indexRoute
  '/_authed/settings': typeof settingsRoute
  '/_authed/projects/': typeof projectsRoute
  '/_authed/projects/$projectId': typeof projectLayoutRouteWithChildren
  '/_authed/projects/$projectId/': typeof projectOverviewRoute
  '/_authed/projects/$projectId/budget': typeof projectBudgetRoute
  '/_authed/projects/$projectId/chat': typeof projectChatRoute
  '/_authed/projects/$projectId/design': typeof projectDesignRoute
  '/_authed/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/_authed/projects/$projectId/photos': typeof projectPhotosRoute
  '/_authed/projects/$projectId/plan': typeof projectPlanRoute
  '/_authed/projects/$projectId/progress': typeof projectProgressRoute
  '/_authed/projects/$projectId/stages': typeof projectStagesRoute
  '/_authed/projects/$projectId/team': typeof projectTeamRoute
  '/_authed/projects/$projectId/updates': typeof projectUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/projects/'
    | '/projects/$projectId'
    | '/projects/$projectId/'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/design'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/plan'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/settings'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/design'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/plan'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/updates'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/'
    | '/_authed/settings'
    | '/_authed/projects/'
    | '/_authed/projects/$projectId'
    | '/_authed/projects/$projectId/'
    | '/_authed/projects/$projectId/budget'
    | '/_authed/projects/$projectId/chat'
    | '/_authed/projects/$projectId/design'
    | '/_authed/projects/$projectId/knowledge'
    | '/_authed/projects/$projectId/photos'
    | '/_authed/projects/$projectId/plan'
    | '/_authed/projects/$projectId/progress'
    | '/_authed/projects/$projectId/stages'
    | '/_authed/projects/$projectId/team'
    | '/_authed/projects/$projectId/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRoute: typeof authedRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof settingsRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof projectsRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof projectLayoutRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof projectOverviewRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/budget': {
      id: '/_authed/projects/$projectId/budget'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof projectBudgetRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/chat': {
      id: '/_authed/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof projectChatRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/design': {
      id: '/_authed/projects/$projectId/design'
      path: '/design'
      fullPath: '/projects/$projectId/design'
      preLoaderRoute: typeof projectDesignRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/knowledge': {
      id: '/_authed/projects/$projectId/knowledge'
      path: '/knowledge'
      fullPath: '/projects/$projectId/knowledge'
      preLoaderRoute: typeof projectKnowledgeRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/photos': {
      id: '/_authed/projects/$projectId/photos'
      path: '/photos'
      fullPath: '/projects/$projectId/photos'
      preLoaderRoute: typeof projectPhotosRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/plan': {
      id: '/_authed/projects/$projectId/plan'
      path: '/plan'
      fullPath: '/projects/$projectId/plan'
      preLoaderRoute: typeof projectPlanRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/progress': {
      id: '/_authed/projects/$projectId/progress'
      path: '/progress'
      fullPath: '/projects/$projectId/progress'
      preLoaderRoute: typeof projectProgressRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/stages': {
      id: '/_authed/projects/$projectId/stages'
      path: '/stages'
      fullPath: '/projects/$projectId/stages'
      preLoaderRoute: typeof projectStagesRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/team': {
      id: '/_authed/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof projectTeamRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/updates': {
      id: '/_authed/projects/$projectId/updates'
      path: '/updates'
      fullPath: '/projects/$projectId/updates'
      preLoaderRoute: typeof projectUpdatesRouteImport
      parentRoute: typeof projectLayoutRoute
    }
  }
}

interface projectLayoutRouteChildren {
  projectOverviewRoute: typeof projectOverviewRoute
  projectBudgetRoute: typeof projectBudgetRoute
  projectChatRoute: typeof projectChatRoute
  projectDesignRoute: typeof projectDesignRoute
  projectKnowledgeRoute: typeof projectKnowledgeRoute
  projectPhotosRoute: typeof projectPhotosRoute
  projectPlanRoute: typeof projectPlanRoute
  projectProgressRoute: typeof projectProgressRoute
  projectStagesRoute: typeof projectStagesRoute
  projectTeamRoute: typeof projectTeamRoute
  projectUpdatesRoute: typeof projectUpdatesRoute
}

const projectLayoutRouteChildren: projectLayoutRouteChildren = {
  projectOverviewRoute: projectOverviewRoute,
  projectBudgetRoute: projectBudgetRoute,
  projectChatRoute: projectChatRoute,
  projectDesignRoute: projectDesignRoute,
  projectKnowledgeRoute: projectKnowledgeRoute,
  projectPhotosRoute: projectPhotosRoute,
  projectPlanRoute: projectPlanRoute,
  projectProgressRoute: projectProgressRoute,
  projectStagesRoute: projectStagesRoute,
  projectTeamRoute: projectTeamRoute,
  projectUpdatesRoute: projectUpdatesRoute,
}

const projectLayoutRouteWithChildren = projectLayoutRoute._addFileChildren(
  projectLayoutRouteChildren,
)

interface authedRouteChildren {
  indexRoute: typeof indexRoute
  settingsRoute: typeof settingsRoute
  projectsRoute: typeof projectsRoute
  projectLayoutRoute: typeof projectLayoutRouteWithChildren
}

const authedRouteChildren: authedRouteChildren = {
  indexRoute: indexRoute,
  settingsRoute: settingsRoute,
  projectsRoute: projectsRoute,
  projectLayoutRoute: projectLayoutRouteWithChildren,
}

const authedRouteWithChildren =
  authedRoute._addFileChildren(authedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authedRoute: authedRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
