/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteImport } from './routes/_authed'
import { Route as forgotPasswordRouteImport } from './routes/forgot-password'
import { Route as loginRouteImport } from './routes/login'
import { Route as mfaLayoutRouteImport } from './routes/mfa/layout'
import { Route as resetPasswordRouteImport } from './routes/reset-password'
import { Route as indexRouteImport } from './routes/index'
import { Route as mfaChallengeRouteImport } from './routes/mfa/challenge'
import { Route as mfaEnrollRouteImport } from './routes/mfa/enroll'
import { Route as projectsRouteImport } from './routes/projects'
import { Route as projectLayoutRouteImport } from './routes/project/layout'
import { Route as settingsIndexRouteImport } from './routes/settings/index'
import { Route as settingsProfileRouteImport } from './routes/settings/profile'
import { Route as settingsSecurityRouteImport } from './routes/settings/security'
import { Route as projectOverviewRouteImport } from './routes/project/overview'
import { Route as projectBudgetRouteImport } from './routes/project/budget'
import { Route as projectChatRouteImport } from './routes/project/chat'
import { Route as projectDesignRouteImport } from './routes/project/design'
import { Route as projectDocumentsRouteImport } from './routes/project/documents'
import { Route as projectKnowledgeRouteImport } from './routes/project/knowledge'
import { Route as projectPhotosRouteImport } from './routes/project/photos'
import { Route as projectPlanRouteImport } from './routes/project/plan'
import { Route as projectProgressRouteImport } from './routes/project/progress'
import { Route as projectStagesRouteImport } from './routes/project/stages'
import { Route as projectTeamRouteImport } from './routes/project/team'
import { Route as projectUpdatesRouteImport } from './routes/project/updates'
import { Route as projectRoomRouteImport } from './routes/project/room'

const authedRoute = authedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const forgotPasswordRoute = forgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mfaLayoutRoute = mfaLayoutRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const resetPasswordRoute = resetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedRoute,
} as any)
const mfaChallengeRoute = mfaChallengeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mfaLayoutRoute,
} as any)
const mfaEnrollRoute = mfaEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => mfaLayoutRoute,
} as any)
const projectsRoute = projectsRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => authedRoute,
} as any)
const projectLayoutRoute = projectLayoutRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => authedRoute,
} as any)
const settingsIndexRoute = settingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => authedRoute,
} as any)
const settingsProfileRoute = settingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => authedRoute,
} as any)
const settingsSecurityRoute = settingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => authedRoute,
} as any)
const projectOverviewRoute = projectOverviewRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectBudgetRoute = projectBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectChatRoute = projectChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectDesignRoute = projectDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectDocumentsRoute = projectDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectKnowledgeRoute = projectKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectPhotosRoute = projectPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectPlanRoute = projectPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectProgressRoute = projectProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectStagesRoute = projectStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectTeamRoute = projectTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectUpdatesRoute = projectUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => projectLayoutRoute,
} as any)
const projectRoomRoute = projectRoomRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => projectLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/forgot-password': typeof forgotPasswordRoute
  '/login': typeof loginRoute
  '/mfa': typeof mfaLayoutRouteWithChildren
  '/reset-password': typeof resetPasswordRoute
  '/mfa/': typeof mfaChallengeRoute
  '/mfa/enroll': typeof mfaEnrollRoute
  '/projects/': typeof projectsRoute
  '/projects/$projectId': typeof projectLayoutRouteWithChildren
  '/settings/profile': typeof settingsProfileRoute
  '/settings/security': typeof settingsSecurityRoute
  '/settings/': typeof settingsIndexRoute
  '/projects/$projectId/': typeof projectOverviewRoute
  '/projects/$projectId/budget': typeof projectBudgetRoute
  '/projects/$projectId/chat': typeof projectChatRoute
  '/projects/$projectId/design': typeof projectDesignRoute
  '/projects/$projectId/documents': typeof projectDocumentsRoute
  '/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/projects/$projectId/photos': typeof projectPhotosRoute
  '/projects/$projectId/plan': typeof projectPlanRoute
  '/projects/$projectId/progress': typeof projectProgressRoute
  '/projects/$projectId/stages': typeof projectStagesRoute
  '/projects/$projectId/team': typeof projectTeamRoute
  '/projects/$projectId/updates': typeof projectUpdatesRoute
  '/projects/$projectId/rooms/$roomId': typeof projectRoomRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof forgotPasswordRoute
  '/login': typeof loginRoute
  '/reset-password': typeof resetPasswordRoute
  '/': typeof indexRoute
  '/mfa': typeof mfaChallengeRoute
  '/mfa/enroll': typeof mfaEnrollRoute
  '/projects': typeof projectsRoute
  '/settings/profile': typeof settingsProfileRoute
  '/settings/security': typeof settingsSecurityRoute
  '/settings': typeof settingsIndexRoute
  '/projects/$projectId': typeof projectOverviewRoute
  '/projects/$projectId/budget': typeof projectBudgetRoute
  '/projects/$projectId/chat': typeof projectChatRoute
  '/projects/$projectId/design': typeof projectDesignRoute
  '/projects/$projectId/documents': typeof projectDocumentsRoute
  '/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/projects/$projectId/photos': typeof projectPhotosRoute
  '/projects/$projectId/plan': typeof projectPlanRoute
  '/projects/$projectId/progress': typeof projectProgressRoute
  '/projects/$projectId/stages': typeof projectStagesRoute
  '/projects/$projectId/team': typeof projectTeamRoute
  '/projects/$projectId/updates': typeof projectUpdatesRoute
  '/projects/$projectId/rooms/$roomId': typeof projectRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof authedRouteWithChildren
  '/forgot-password': typeof forgotPasswordRoute
  '/login': typeof loginRoute
  '/mfa': typeof mfaLayoutRouteWithChildren
  '/reset-password': typeof resetPasswordRoute
  '/_authed/': typeof indexRoute
  '/mfa/': typeof mfaChallengeRoute
  '/mfa/enroll': typeof mfaEnrollRoute
  '/_authed/projects/': typeof projectsRoute
  '/_authed/projects/$projectId': typeof projectLayoutRouteWithChildren
  '/_authed/settings/profile': typeof settingsProfileRoute
  '/_authed/settings/security': typeof settingsSecurityRoute
  '/_authed/settings/': typeof settingsIndexRoute
  '/_authed/projects/$projectId/': typeof projectOverviewRoute
  '/_authed/projects/$projectId/budget': typeof projectBudgetRoute
  '/_authed/projects/$projectId/chat': typeof projectChatRoute
  '/_authed/projects/$projectId/design': typeof projectDesignRoute
  '/_authed/projects/$projectId/documents': typeof projectDocumentsRoute
  '/_authed/projects/$projectId/knowledge': typeof projectKnowledgeRoute
  '/_authed/projects/$projectId/photos': typeof projectPhotosRoute
  '/_authed/projects/$projectId/plan': typeof projectPlanRoute
  '/_authed/projects/$projectId/progress': typeof projectProgressRoute
  '/_authed/projects/$projectId/stages': typeof projectStagesRoute
  '/_authed/projects/$projectId/team': typeof projectTeamRoute
  '/_authed/projects/$projectId/updates': typeof projectUpdatesRoute
  '/_authed/projects/$projectId/rooms/$roomId': typeof projectRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/reset-password'
    | '/mfa/'
    | '/mfa/enroll'
    | '/projects/'
    | '/projects/$projectId'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/'
    | '/projects/$projectId/'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/design'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/plan'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/updates'
    | '/projects/$projectId/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/mfa'
    | '/mfa/enroll'
    | '/projects'
    | '/settings/profile'
    | '/settings/security'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/design'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/knowledge'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/plan'
    | '/projects/$projectId/progress'
    | '/projects/$projectId/stages'
    | '/projects/$projectId/team'
    | '/projects/$projectId/updates'
    | '/projects/$projectId/rooms/$roomId'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/mfa'
    | '/reset-password'
    | '/_authed/'
    | '/mfa/'
    | '/mfa/enroll'
    | '/_authed/projects/'
    | '/_authed/projects/$projectId'
    | '/_authed/settings/profile'
    | '/_authed/settings/security'
    | '/_authed/settings/'
    | '/_authed/projects/$projectId/'
    | '/_authed/projects/$projectId/budget'
    | '/_authed/projects/$projectId/chat'
    | '/_authed/projects/$projectId/design'
    | '/_authed/projects/$projectId/documents'
    | '/_authed/projects/$projectId/knowledge'
    | '/_authed/projects/$projectId/photos'
    | '/_authed/projects/$projectId/plan'
    | '/_authed/projects/$projectId/progress'
    | '/_authed/projects/$projectId/stages'
    | '/_authed/projects/$projectId/team'
    | '/_authed/projects/$projectId/updates'
    | '/_authed/projects/$projectId/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRoute: typeof authedRouteWithChildren
  forgotPasswordRoute: typeof forgotPasswordRoute
  loginRoute: typeof loginRoute
  mfaLayoutRoute: typeof mfaLayoutRouteWithChildren
  resetPasswordRoute: typeof resetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof forgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof mfaLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof resetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof authedRoute
    }
    '/mfa/': {
      id: '/mfa/'
      path: '/'
      fullPath: '/mfa/'
      preLoaderRoute: typeof mfaChallengeRouteImport
      parentRoute: typeof mfaLayoutRoute
    }
    '/mfa/enroll': {
      id: '/mfa/enroll'
      path: '/enroll'
      fullPath: '/mfa/enroll'
      preLoaderRoute: typeof mfaEnrollRouteImport
      parentRoute: typeof mfaLayoutRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof projectsRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof projectLayoutRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof settingsIndexRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof settingsProfileRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof settingsSecurityRouteImport
      parentRoute: typeof authedRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof projectOverviewRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/budget': {
      id: '/_authed/projects/$projectId/budget'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof projectBudgetRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/chat': {
      id: '/_authed/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof projectChatRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/design': {
      id: '/_authed/projects/$projectId/design'
      path: '/design'
      fullPath: '/projects/$projectId/design'
      preLoaderRoute: typeof projectDesignRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/documents': {
      id: '/_authed/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof projectDocumentsRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/knowledge': {
      id: '/_authed/projects/$projectId/knowledge'
      path: '/knowledge'
      fullPath: '/projects/$projectId/knowledge'
      preLoaderRoute: typeof projectKnowledgeRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/photos': {
      id: '/_authed/projects/$projectId/photos'
      path: '/photos'
      fullPath: '/projects/$projectId/photos'
      preLoaderRoute: typeof projectPhotosRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/plan': {
      id: '/_authed/projects/$projectId/plan'
      path: '/plan'
      fullPath: '/projects/$projectId/plan'
      preLoaderRoute: typeof projectPlanRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/progress': {
      id: '/_authed/projects/$projectId/progress'
      path: '/progress'
      fullPath: '/projects/$projectId/progress'
      preLoaderRoute: typeof projectProgressRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/stages': {
      id: '/_authed/projects/$projectId/stages'
      path: '/stages'
      fullPath: '/projects/$projectId/stages'
      preLoaderRoute: typeof projectStagesRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/team': {
      id: '/_authed/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof projectTeamRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/updates': {
      id: '/_authed/projects/$projectId/updates'
      path: '/updates'
      fullPath: '/projects/$projectId/updates'
      preLoaderRoute: typeof projectUpdatesRouteImport
      parentRoute: typeof projectLayoutRoute
    }
    '/_authed/projects/$projectId/rooms/$roomId': {
      id: '/_authed/projects/$projectId/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/projects/$projectId/rooms/$roomId'
      preLoaderRoute: typeof projectRoomRouteImport
      parentRoute: typeof projectLayoutRoute
    }
  }
}

interface projectLayoutRouteChildren {
  projectOverviewRoute: typeof projectOverviewRoute
  projectBudgetRoute: typeof projectBudgetRoute
  projectChatRoute: typeof projectChatRoute
  projectDesignRoute: typeof projectDesignRoute
  projectDocumentsRoute: typeof projectDocumentsRoute
  projectKnowledgeRoute: typeof projectKnowledgeRoute
  projectPhotosRoute: typeof projectPhotosRoute
  projectPlanRoute: typeof projectPlanRoute
  projectProgressRoute: typeof projectProgressRoute
  projectStagesRoute: typeof projectStagesRoute
  projectTeamRoute: typeof projectTeamRoute
  projectUpdatesRoute: typeof projectUpdatesRoute
  projectRoomRoute: typeof projectRoomRoute
}

const projectLayoutRouteChildren: projectLayoutRouteChildren = {
  projectOverviewRoute: projectOverviewRoute,
  projectBudgetRoute: projectBudgetRoute,
  projectChatRoute: projectChatRoute,
  projectDesignRoute: projectDesignRoute,
  projectDocumentsRoute: projectDocumentsRoute,
  projectKnowledgeRoute: projectKnowledgeRoute,
  projectPhotosRoute: projectPhotosRoute,
  projectPlanRoute: projectPlanRoute,
  projectProgressRoute: projectProgressRoute,
  projectStagesRoute: projectStagesRoute,
  projectTeamRoute: projectTeamRoute,
  projectUpdatesRoute: projectUpdatesRoute,
  projectRoomRoute: projectRoomRoute,
}

const projectLayoutRouteWithChildren = projectLayoutRoute._addFileChildren(
  projectLayoutRouteChildren,
)

interface authedRouteChildren {
  indexRoute: typeof indexRoute
  projectsRoute: typeof projectsRoute
  projectLayoutRoute: typeof projectLayoutRouteWithChildren
  settingsProfileRoute: typeof settingsProfileRoute
  settingsSecurityRoute: typeof settingsSecurityRoute
  settingsIndexRoute: typeof settingsIndexRoute
}

const authedRouteChildren: authedRouteChildren = {
  indexRoute: indexRoute,
  projectsRoute: projectsRoute,
  projectLayoutRoute: projectLayoutRouteWithChildren,
  settingsProfileRoute: settingsProfileRoute,
  settingsSecurityRoute: settingsSecurityRoute,
  settingsIndexRoute: settingsIndexRoute,
}

const authedRouteWithChildren =
  authedRoute._addFileChildren(authedRouteChildren)

interface mfaLayoutRouteChildren {
  mfaChallengeRoute: typeof mfaChallengeRoute
  mfaEnrollRoute: typeof mfaEnrollRoute
}

const mfaLayoutRouteChildren: mfaLayoutRouteChildren = {
  mfaChallengeRoute: mfaChallengeRoute,
  mfaEnrollRoute: mfaEnrollRoute,
}

const mfaLayoutRouteWithChildren = mfaLayoutRoute._addFileChildren(
  mfaLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedRoute: authedRouteWithChildren,
  forgotPasswordRoute: forgotPasswordRoute,
  loginRoute: loginRoute,
  mfaLayoutRoute: mfaLayoutRouteWithChildren,
  resetPasswordRoute: resetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
